#include "lib.h" 

#define message1 "Error couldnt open file\n"
#define message2 "Error couldnt close file\n"
#define message3 "Correct syntax is: ./fss_manager -l <manager_logfile> -c <config_file> -n <worker_limit>\n"
#define message4 "Error while using seek\n"
#define message5 "Error couldn't create child with fork\n"
#define message6 "Error mkfifo failed\n"
#define message8 "Error couldnt create pipe\n"
#define message9 "Error malloc failed\n"
#define message10 "Failed to watch directory\n"
#define message11 "opendir failed"
#define message12 "Failed to watch source directory\n"
#define message13 "Failed to watch file\n" 